name: Deploy static site
on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Sync site to S3 (bucket in ca-central-1)
        run: aws s3 sync site/ s3://chrys-aws-static-site-123 --region ca-central-1 --delete

      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id E24P9YW5EITBF8 --paths "/*"
